//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBenhVien.Model
{
    using QLBenhVien.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class BHYT:BaseViewModel
    {
        public int IdPatient { get; set; }

        string _CodeBHYT;
        public string CodeBHYT { get => _CodeBHYT; set { _CodeBHYT = value; OnPropertyChanged(); } }

        Nullable<System.DateTime> _DateStart;
        public Nullable<System.DateTime> DateStart { get => _DateStart; set { _DateStart = value; OnPropertyChanged(); } }

        Nullable<System.DateTime> _DateEnd;
        public Nullable<System.DateTime> DateEnd { get => _DateEnd; set { _DateEnd = value; OnPropertyChanged(); } }

        string _Reduction;
        public string Reduction { get => _Reduction; set { _Reduction = value; OnPropertyChanged(); } }

        public virtual Patient Patient { get; set; }
    }
}
