//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBenhVien.Model
{
    using QLBenhVien.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalFee:BaseViewModel
    {
        public int IdMedicalRecord { get; set; }

        decimal _TotalFee;
        public decimal TotalFee { get => _TotalFee; set { _TotalFee = value; OnPropertyChanged(); } }

        Nullable<decimal> _Owed;
        public Nullable<decimal> Owed { get => _Owed; set { _Owed = value; OnPropertyChanged(); } }

        public virtual MedicalRecord MedicalRecord { get; set; }
    }
}
