//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBenhVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecord
    {
        public int Id { get; set; }
        public int IdPatient { get; set; }
        public int IdSick { get; set; }
        public Nullable<int> IdPrescription { get; set; }
        public int IdLocation { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
    
        public virtual HospitalFee HospitalFee { get; set; }
        public virtual Location Location { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Prescription Prescription { get; set; }
        public virtual Sick Sick { get; set; }
    }
}
