//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBenhVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuantityMedicine
    {
        public int Id { get; set; }
        public int IdPrescription { get; set; }
        public int IdMedicine { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
